/**
 * @file GenerationPanel.tsx
 * @description This component provides the UI for generating text from the trained model.
 * It allows users to set a seed token and temperature, generate a word, and then provide
 * feedback (coaching) to reinforce good outputs. It also contains the controls and display
 * for the automated "Auto Coach" feature.
 */

import React, { useState, useEffect, useRef } from 'react';
import { LanguageModel } from '../types';
import { generateFFNN, generateRNN, generateGRU, generateLSTM } from '../services/languageModel';
import { SparklesIcon, DownloadIcon, StopIcon } from './icons';
import { Tooltip } from './Tooltip';

/**
 * Renders the generation controls, output display, and coaching interface.
 * @param {object} props - The component's props.
 */
export const GenerationPanel = ({ model, coachingEnabled, onReinforce, isAutoCoaching, onToggleAutoCoach, autoCoachedWords, newWordsLog, coachingStatsLog, onDownloadNewWords }) => {
  // --- State ---
  // The starting token for generation.
  const [seed, setSeed] = useState('');
  // Controls the randomness of the output. Higher values = more creative.
  const [temperature, setTemperature] = useState(1.1);
  // The text generated by the model.
  const [generatedText, setGeneratedText] = useState('');
  // Flag to indicate if generation is in progress.
  const [isGenerating, setIsGenerating] = useState(false);
  // Flag to show/hide the manual coaching buttons (Good/Bad).
  const [showCoaching, setShowCoaching] = useState(false);
  // Ref to the auto-coaching log container for scrolling.
  const logContainerRef = useRef<HTMLDivElement>(null);

  /**
   * Effect to automatically select a random, valid seed token when the model changes.
   */
  useEffect(() => {
    if (model && model.vocab && model.vocab.length > 0) {
      const nonSpaceVocab = model.vocab.filter(c => c.trim() !== '');
      if (nonSpaceVocab.length > 0) {
        const randomIndex = Math.floor(Math.random() * nonSpaceVocab.length);
        setSeed(nonSpaceVocab[randomIndex]);
      } else if (model.vocab.length > 0) {
        setSeed(model.vocab[0]);
      }
    }
  }, [model]);

  /**
   * Effect to automatically scroll the auto-coaching log to the bottom as new words are added.
   */
  useEffect(() => {
    if (logContainerRef.current) {
        logContainerRef.current.scrollTop = logContainerRef.current.scrollHeight;
    }
  }, [autoCoachedWords]);

  /**
   * Effect to clean up the UI when auto-coaching starts.
   */
  useEffect(() => {
    if (isAutoCoaching) {
        setGeneratedText('');
        setShowCoaching(false);
    }
  }, [isAutoCoaching]);

  /**
   * Handles the "Generate Word" button click.
   * It calls the appropriate generation function based on the model type.
   */
  const handleGenerate = () => {
    if (!model || !seed) return;
    setIsGenerating(true);
    setGeneratedText('');
    setShowCoaching(false);
    
    // Use a short timeout to allow the UI to update to "Generating..." before the blocking generation call.
    setTimeout(() => {
        let result = '';
        const maxLength = 50; // Max length of a generated word.
        if (model.type === 'FFNN') {
            result = generateFFNN(model, seed, maxLength, temperature);
        } else if (model.type === 'RNN') {
            result = generateRNN(model, seed, maxLength, temperature);
        } else if (model.type === 'GRU') {
            result = generateGRU(model, seed, maxLength, temperature);
        } else if (model.type === 'LSTM') {
            result = generateLSTM(model, seed, maxLength, temperature);
        }
        setGeneratedText(result);
        setIsGenerating(false);
        setShowCoaching(true); // Show coaching buttons after generation.
    }, 10);
  };

  /**
   * Handles the "Good 👍" button click, triggering the reinforcement callback.
   */
  const handleReinforceClick = () => {
    if (onReinforce) {
        onReinforce(generatedText);
    }
    setShowCoaching(false);
  }
  
  /**
   * Handles the "Bad 👎" button click.
   */
  const handleDismissClick = () => {
    setShowCoaching(false);
  }

  /**
   * Handles downloading the manually generated word as a text file.
   */
  const handleDownloadGenerated = () => {
    const blob = new Blob([generatedText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'generated-word.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };
  
  // --- Derived stats for the auto-coaching display ---
  const totalGoodCount = autoCoachedWords.filter(w => w.isGood).length;
  const last30Words = autoCoachedWords.slice(-30);
  const goodCountLast30 = last30Words.filter(w => w.isGood).length;
  const badCountLast30 = last30Words.length - goodCountLast30;

  return (
    <>
      <p className="text-sm text-gray-400 mb-4">
        Generate a word, then provide feedback. Or, use Auto Coach to let the app find and reinforce good words automatically.
      </p>
      
      {/* --- Generation Controls (Seed & Temperature) --- */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
        <div className="space-y-2">
            <Tooltip text="The starting token for generation. A random one is chosen automatically.">
                <label htmlFor="seed-select" className="block text-sm font-medium text-gray-300">Seed Token</label>
            </Tooltip>
            <select
                id="seed-select"
                value={seed}
                onChange={(e) => setSeed(e.target.value)}
                disabled={!model || isGenerating || isAutoCoaching}
                className="w-full p-2 bg-gray-900 border border-gray-700 rounded-md font-mono text-sm disabled:opacity-50"
            >
                {model?.vocab?.filter(token => token.trim() !== '').map(token => (
                    <option key={token} value={token}>{token}</option>
                ))}
            </select>
        </div>
        <div className="space-y-2">
            <Tooltip text="Controls the randomness of the output. Higher values are more creative, lower values are more predictable.">
                <label htmlFor="temperature" className="block text-sm font-medium text-gray-300">
                    Temperature: <span className="font-mono bg-gray-900 px-2 py-1 rounded-md">{temperature.toFixed(2)}</span>
                </label>
            </Tooltip>
            <input
                id="temperature"
                type="range"
                min="0.1" max="1.5" step="0.05"
                value={temperature}
                onChange={(e) => setTemperature(parseFloat(e.target.value))}
                disabled={!model || isGenerating || isAutoCoaching}
                className="w-full h-2 bg-gray-700 rounded-lg appearance-none cursor-pointer disabled:opacity-50"
            />
        </div>
      </div>
      
       {/* --- Action Buttons (Generate & Auto Coach) --- */}
       <div className="grid grid-cols-2 gap-4 mb-4">
        <button
          onClick={handleGenerate}
          disabled={!model || isGenerating || isAutoCoaching}
          className="w-full flex items-center justify-center px-4 py-2 bg-cyan-600 hover:bg-cyan-700 rounded-md font-semibold transition-colors duration-200 text-white disabled:bg-gray-600 disabled:cursor-not-allowed"
        >
          <SparklesIcon className="w-5 h-5 mr-2" />
          {isGenerating ? 'Generating...' : 'Generate Word'}
        </button>
        <button
          onClick={onToggleAutoCoach}
          disabled={!model || isGenerating}
          className={`w-full flex items-center justify-center px-4 py-2 rounded-md font-semibold transition-colors duration-200 text-white disabled:bg-gray-600 disabled:cursor-not-allowed ${
            isAutoCoaching ? 'bg-orange-600 hover:bg-orange-700' : 'bg-purple-600 hover:bg-purple-700'
          }`}
        >
          {isAutoCoaching ? <StopIcon className="w-5 h-5 mr-2" /> : <SparklesIcon className="w-5 h-5 mr-2" />}
          {isAutoCoaching ? 'Stop Auto Coach' : 'Auto Coach'}
        </button>
      </div>

      {/* --- Output Display Area --- */}
      {/* This area conditionally renders either the manual generation output or the auto-coaching log. */}
      <div className="flex-grow bg-gray-900 p-3 rounded-md border border-gray-700 min-h-[150px] relative flex flex-col">
         {isAutoCoaching ? (
          // Auto-coaching view
          <div ref={logContainerRef} className="overflow-y-auto h-full">
             <p className="text-center text-sm text-gray-400 mb-2 sticky top-0 bg-gray-900 py-1 font-mono">
                {`Auto-coaching... Total Good: ${totalGoodCount} | Good/Bad (last 30): ${goodCountLast30}/${badCountLast30}`}
             </p>
             <div className="flex flex-wrap gap-x-4 gap-y-1 justify-center font-mono">
                {autoCoachedWords.map((item, index) => (
                    <span key={index} className={item.isGood ? 'text-green-400' : 'text-red-500/60'}>
                        {item.word}
                    </span>
                ))}
             </div>
          </div>
        ) : (
          // Manual generation view
          <>
            <pre className="text-2xl font-mono text-cyan-300 whitespace-pre-wrap break-words tracking-widest flex-grow">
                {generatedText || (!model ? "Model not initialized." : "Click 'Generate Word' to see the model's output.")}
            </pre>
            {generatedText && (
                <Tooltip text="Download generated word">
                    <button onClick={handleDownloadGenerated} className="absolute top-2 right-2 p-1.5 text-gray-400 hover:text-white bg-gray-700/50 hover:bg-gray-600 rounded-md">
                        <DownloadIcon className="w-4 h-4" />
                    </button>
                </Tooltip>
            )}
            {/* Manual coaching buttons appear after generation */}
            {showCoaching && (
                <div className="flex-shrink-0 pt-2 border-t border-gray-700/50 mt-2">
                    <p className="text-xs text-center text-gray-400 mb-2">Was this a good word?</p>
                    <div className="flex justify-center space-x-2">
                        <Tooltip text="Reinforces the entire sequence of predictions that made this word. This runs a targeted training loop on each token-to-token step multiple times, strengthening the connections that led to this successful outcome.">
                            <button
                                onClick={handleReinforceClick}
                                disabled={!coachingEnabled}
                                className="px-4 py-1 text-sm rounded-md bg-green-600 hover:bg-green-700 disabled:bg-gray-500 disabled:cursor-not-allowed"
                            >
                                Good 👍
                            </button>
                        </Tooltip>
                        <Tooltip text="Dismiss this word. No changes are made to the model.">
                            <button
                                onClick={handleDismissClick}
                                disabled={!coachingEnabled}
                                className="px-4 py-1 text-sm rounded-md bg-red-600 hover:bg-red-700 disabled:bg-gray-500 disabled:cursor-not-allowed"
                            >
                                Bad 👎
                            </button>
                        </Tooltip>
                    </div>
                </div>
            )}
          </>
        )}
      </div>
      
       {/* --- Cyclical Training Report Section --- */}
       {/* This section only appears when cyclical training has produced logs. */}
       {(coachingStatsLog.length > 0 || newWordsLog.length > 0) && (
        <div className="mt-4 pt-4 border-t border-gray-700 space-y-4 bg-gray-800 p-4 rounded-lg">
            <h3 className="text-lg font-semibold text-cyan-400">Cyclical Training Report</h3>
            {coachingStatsLog.length > 0 && (
                <div>
                    <h4 className="text-md font-medium text-gray-300 mb-2">Coaching Session Stats</h4>
                    <ul className="text-xs font-mono text-gray-400 bg-gray-900 p-2 rounded-md space-y-1 max-h-24 overflow-y-auto">
                        {coachingStatsLog.map((log, i) => <li key={i}>{log}</li>)}
                    </ul>
                </div>
            )}
            {newWordsLog.length > 0 && (
                <div>
                    <div className="flex justify-between items-center mb-2">
                        <h4 className="text-md font-medium text-gray-300">New Words Discovered</h4>
                        <Tooltip text="Download list of new words">
                          <button onClick={onDownloadNewWords} className="p-1.5 text-gray-400 hover:text-white bg-gray-700/50 hover:bg-gray-600 rounded-md">
                              <DownloadIcon className="w-4 h-4" />
                          </button>
                        </Tooltip>
                    </div>
                    <p className="font-mono text-sm text-green-300 bg-gray-900 p-2 rounded-md h-24 overflow-y-auto">
                      {newWordsLog.join(' ')}
                    </p>
                </div>
            )}
        </div>
      )}
    </>
  );
};
