
import React from 'react';

export const GenerationHistoryPanel = ({ history }) => {
  if (history.length === 0) {
    return (
      <div className="flex-grow flex flex-col items-center justify-center min-h-[150px]">
        <p className="text-gray-400 mt-4 text-center">This panel will show words generated by the model after training is complete.</p>
      </div>
    );
  }

  return (
    <div className="flex-grow flex flex-col overflow-hidden">
      <p className="text-sm text-gray-400 mb-4 flex-shrink-0">
        Words generated by the model at different stages of training.
      </p>
      <div className="flex-grow overflow-auto h-48">
        <ul className="space-y-4">
          {history.map(({ epoch, words }) => (
            <li key={epoch} className="bg-gray-900/50 p-3 rounded-md border border-gray-700">
              <h3 className="font-semibold text-gray-300">After Epoch {epoch}</h3>
              <p className="font-mono text-lg tracking-widest text-cyan-300 mt-1">
                {words.join(' ')}
              </p>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};